[project]
name = "skm"
version = "0.1.0"
description = "A simple CLI to manage Agentic Skills from public repositories"
readme = "README.md"
authors = [
    { name = "Raul De Maio", email = "rauldemaio@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
skm = "skm:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
